/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.EspecialidadeDao;
import javax.swing.JOptionPane;
import javax.swing.JTable;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22282183
 */
public class EspecialidadesPanel extends javax.swing.JPanel {

    /**
     * Creates new form EspecialidadesPanel
     */
    public EspecialidadesPanel() {
        initComponents();
        EspecialidadeDao.criarListaEspecialidades();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEspecialidadesJTablel = new javax.swing.JTable();
        excluirEspecialidadeButton = new javax.swing.JButton();
        editarEspecialidadeJButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lista de Especialidades", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        setPreferredSize(new java.awt.Dimension(750, 380));
        setLayout(null);

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/atualizar.png"))); // NOI18N
        updateButton.setToolTipText("carregar");
        updateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton);
        updateButton.setBounds(510, 280, 70, 50);

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/mais.png"))); // NOI18N
        editarButton.setToolTipText("Adicionar");
        editarButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        add(editarButton);
        editarButton.setBounds(670, 280, 70, 50);

        tabelaEspecialidadesJTablel.setAutoCreateRowSorter(true);
        tabelaEspecialidadesJTablel.setBackground(new java.awt.Color(255, 204, 51));
        tabelaEspecialidadesJTablel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaEspecialidadesJTablel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tabelaEspecialidadesJTablel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaEspecialidadesJTablel.setSelectionBackground(new java.awt.Color(228, 53, 88));
        jScrollPane2.setViewportView(tabelaEspecialidadesJTablel);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 730, 250);

        excluirEspecialidadeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/excluir (1).png"))); // NOI18N
        excluirEspecialidadeButton.setToolTipText("excluir");
        excluirEspecialidadeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        excluirEspecialidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirEspecialidadeButtonActionPerformed(evt);
            }
        });
        add(excluirEspecialidadeButton);
        excluirEspecialidadeButton.setBounds(10, 280, 60, 60);

        editarEspecialidadeJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/lapis (3).png"))); // NOI18N
        editarEspecialidadeJButton1.setToolTipText("editar");
        editarEspecialidadeJButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        editarEspecialidadeJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEspecialidadeJButton1ActionPerformed(evt);
            }
        });
        add(editarEspecialidadeJButton1);
        editarEspecialidadeJButton1.setBounds(590, 280, 70, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
    
    EspecialidadeDialog especialidadeDialog = new EspecialidadeDialog(null, true);
    especialidadeDialog.setVisible(true);
    preencherTabela();
    
    }//GEN-LAST:event_editarButtonActionPerformed
                                                          
    
    private void excluirEspecialidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirEspecialidadeButtonActionPerformed
       
        int linha = tabelaEspecialidadesJTablel.getSelectedRow();
        
        if (linha != -1) {
        excluirEspecialidade(linha);
        }
        
        
       
    }//GEN-LAST:event_excluirEspecialidadeButtonActionPerformed
    
     private void excluirEspecialidade(int linha) {
        String codigoStr = tabelaEspecialidadesJTablel.getValueAt(linha, 0).toString();
        Integer codigo = Integer.valueOf(codigoStr); 
        
        EspecialidadeDao.excluir(codigo);
        
        preencherTabela();
        }
    
    private void editarEspecialidadeJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEspecialidadeJButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarEspecialidadeJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarButton;
    private javax.swing.JButton editarEspecialidadeJButton1;
    private javax.swing.JButton excluirEspecialidadeButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaEspecialidadesJTablel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
    
    private void preencherTabela (){
        
        tabelaEspecialidadesJTablel.setModel(EspecialidadeDao.getEspecialidadesModel());
        
        
        ajustarTabela();
    }
    
    private void ajustarTabela(){
        //impedir que o usuário movimente as colunas
        tabelaEspecialidadesJTablel.getTableHeader().setReorderingAllowed(true);
        
        //Bloquear a edição das células da tabela
        tabelaEspecialidadesJTablel.setDefaultEditor(Object.class, null);
        
        //
        tabelaEspecialidadesJTablel.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelaEspecialidadesJTablel.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaEspecialidadesJTablel.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaEspecialidadesJTablel.getColumnModel().getColumn(2).setPreferredWidth(400);
        
    }
}
