/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.ui;

import java.awt.Toolkit;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22282213
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/senai/sp/jandira/imagens/relatorio.png")));
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sairButton = new javax.swing.JButton();
        agendaButton = new javax.swing.JButton();
        pacienteButton = new javax.swing.JButton();
        medicosButton = new javax.swing.JButton();
        planosButton = new javax.swing.JButton();
        especialidadesButton = new javax.swing.JButton();
        fundoPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agendamento");
        setBackground(new java.awt.Color(255, 204, 102));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/calendario.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 0, 70, 80);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Sistema para Agendamento de Consultas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 20, 480, 32);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 80);

        sairButton.setBackground(new java.awt.Color(255, 0, 0));
        sairButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sairButton.setForeground(new java.awt.Color(255, 255, 255));
        sairButton.setText("Sair");
        sairButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton);
        sairButton.setBounds(690, 90, 90, 50);

        agendaButton.setBackground(new java.awt.Color(255, 204, 51));
        agendaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agendaButton.setForeground(new java.awt.Color(51, 51, 51));
        agendaButton.setText("Agenda");
        agendaButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        agendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(agendaButton);
        agendaButton.setBounds(10, 90, 100, 50);

        pacienteButton.setBackground(new java.awt.Color(255, 204, 51));
        pacienteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pacienteButton.setForeground(new java.awt.Color(51, 51, 51));
        pacienteButton.setText("Pacientes");
        pacienteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pacienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pacienteButton);
        pacienteButton.setBounds(120, 90, 100, 50);

        medicosButton.setBackground(new java.awt.Color(255, 204, 51));
        medicosButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        medicosButton.setForeground(new java.awt.Color(51, 51, 51));
        medicosButton.setText("Médicos");
        medicosButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        medicosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(medicosButton);
        medicosButton.setBounds(230, 90, 100, 50);

        planosButton.setBackground(new java.awt.Color(255, 204, 51));
        planosButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        planosButton.setForeground(new java.awt.Color(51, 51, 51));
        planosButton.setText("Plano de Saúde");
        planosButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        planosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(planosButton);
        planosButton.setBounds(490, 90, 140, 50);

        especialidadesButton.setBackground(new java.awt.Color(255, 204, 51));
        especialidadesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        especialidadesButton.setForeground(new java.awt.Color(51, 51, 51));
        especialidadesButton.setText("Especialidades");
        especialidadesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        especialidadesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(especialidadesButton);
        especialidadesButton.setBounds(340, 90, 140, 50);

        fundoPanel.setBackground(new java.awt.Color(255, 204, 204));
        fundoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fundoPanel.setLayout(null);

        tabela.setBackground(new java.awt.Color(228, 53, 88));
        tabela.setForeground(new java.awt.Color(255, 204, 204));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.setSelectionBackground(new java.awt.Color(228, 53, 88));
        jScrollPane2.setViewportView(tabela);

        fundoPanel.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 730, 110);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/excluir (1).png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fundoPanel.add(jButton1);
        jButton1.setBounds(10, 310, 60, 60);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/atualizar.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fundoPanel.add(jButton2);
        jButton2.setBounds(590, 320, 70, 50);

        editarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/lapis (3).png"))); // NOI18N
        editarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        fundoPanel.add(editarButton);
        editarButton.setBounds(670, 320, 70, 50);

        getContentPane().add(fundoPanel);
        fundoPanel.setBounds(20, 150, 750, 380);

        setBounds(0, 0, 816, 592);
    }// </editor-fold>//GEN-END:initComponents

    private void medicosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicosButtonActionPerformed

    private void pacienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteButtonActionPerformed

    private void especialidadesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadesButtonActionPerformed

    private void planosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planosButtonActionPerformed

    private void agendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agendaButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendaButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton especialidadesButton;
    private javax.swing.JPanel fundoPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton medicosButton;
    private javax.swing.JButton pacienteButton;
    private javax.swing.JButton planosButton;
    private javax.swing.JButton sairButton;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables


    private void preencherTabela (){
        
        String[][] dados = {
            {"111","abc","sp"},
            {"222","def","sp"},
            {"333","ghi","sp"},
            {"444","jkl","sp"},
            {"555","mno","sp"}
        };
        
        String[] titulos = {"CÓDIGO","Nome da Cidade","Estado"};
        DefaultTableModel modelo = new DefaultTableModel(dados, titulos);
        
        tabela.setModel(modelo);
    }

}


